# Generated by Django 3.2.4 on 2021-06-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_art',
        ),
    ]
