# Generated by Django 3.2.4 on 2021-06-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
